### ISSUE TITLE
Fixturesのcreated_atが設定されません

### ISSUE THREAD

**Issue by logicoffee** [logicoffee/carta_tournaments#17]
原因が全然わからない問題に遭遇してしまいました.

管理者トップページのテストを書くために, 以下のようにfixturesを用意しました.
```yaml
# tournament_classes.yml
advanced_class:
  tournament: shiga
  name: 上級者の部
  fee: 1500
  players: advanced_player
```

```yaml
# players.yml
advanced_player:
  last_name: 福沢
  first_name: 諭吉
  # 以下省略
```

するとテスト実行時に以下のようなエラーが発生してしまいます.
```
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR: \
null value in column "created_at" violates not-null constraint
```
どうやら以下の部分に問題があるようです.
```
INSERT INTO "tournament_classes_players" \
("tournament_class_id", "player_id", "created_at", "updated_at") \
VALUES (874832680, 383792289, DEFAULT, DEFAULT);
```

RailsのIssuesを含めいろいろ調べてみましたが, 答えは得られませんでした...
原因はどこにあるんでしょうか.

**Comment by yubessy** [comment]
ぱっと見た感じ、 `tournament_class` と `players` のアソシエーションを保持する`tournament_classes_players` にタイムスタンプが必要だがどこにも値が設定されていないのが原因のようです。

今後複数大会に拡張するときのため `tournament_class` と `players` は many-to-many にしてあり、 `TournamentClass` 側に `has_and_belongs_to_many` を設定していましたね。
https://github.com/logicoffee/carta_tournaments/blob/master/app/models/tournament_class.rb

`ActiveRecord::Fixtures` では、 `has_and_belongs_to_many` の場合はアソシエーションテーブルのレコードを単体のファイルに定義することもできるようです
https://api.rubyonrails.org/v3.1/classes/ActiveRecord/Fixtures.html

```yaml
### in fruits_monkeys.yml
apple_george:
  fruit_id: 1
  monkey_id: 1
```

これに倣って次のように書いてみてはどうでしょう？

```yaml
# tournament_classes.yml
advanced_class:
  id: 1
  tournament: shiga
  name: ...

advanced_player:
  id: 1
  last_name: ...
  first_name: ...

### tournament_classes_players.yml
advanced_class_player:
  tournament_class_id: 1
  player_id: 1
```

これでも行けなければ timestamp を明示してみるとか

```yaml
### tournament_classes_players.yml
advanced_class_player:
  tournament_class_id: 1
  player_id: 1
  created_at:  <%= Time.now.to_s(:db) %>
  updated_at:  <%= Time.now.to_s(:db) %>
```
